### ISSUE TITLE
一些建议和期待【Some suggestions and expectations】

### ISSUE THREAD

**Issue by huanshiwushuang** [acrazing/html5parser#12]
期待 Utilities。
enter和leave是否有很好的应用场景？
是否可以自定义深度优先或者广度优先？
没有提供去除回车等无用节点的options。
我必须在walk中遍历，但是似乎不能手动停止遍历tree。
如果我在walk中splice无用的节点（比如回车），那么将导致数组的index异常
【
Looking forward to Utilities.
Is there a good application scenario for enter and leave?
Is it possible to customize depth first or breadth first?
There is no option to remove useless nodes such as carriage returns.
I have to traverse in walk, but it seems that I cannot stop traversing the tree manually.
If I splice useless nodes in the walk (such as carriage return), it will cause the index of the array to be abnormal
】

**Comment by acrazing** [comment]
You can write your own `walk` function to iterate the tree, it costs about 20 lines. You can get the example at <https://github.com/acrazing/html5parser/blob/c2324a6016ac819f508b935d88b267e402933438/src/walk.ts#L18-L32>.

**Comment by huanshiwushuang** [comment]
我有查看walk函数的ts源码。
但是我没法在 enter 或者 leave 函数中停止迭代树。
或许可以这样做：
【
I have view the ts source code of the walk function.
But I can't stop iterating the tree in the enter or leave function.
Maybe you can do this:
】

```
function visit(node: INode, parent: INode | undefined, index: number, options: WalkOptions) { 
   let enterReturn = options.enter && options.enter(node, parent, index);
   // 在enter之后停止迭代
   // Stop iteration after enter
   if (enterReturn === false) {
        return enterReturn;
   }
   if (node.type === SyntaxKind.Tag && Array.isArray(node.body)) { 
     for (let i = 0; i < node.body.length; i++) { 
       let visitReturn = visit(node.body[i], node, i, options);
       // 停止迭代子节点
       // Stop iterating child nodes
       if (visitReturn === false) {
            break;
       }
     } 
   } 
   let leaveReturn = options.leave && options.leave(node, parent, index);
   // 在leave之后停止迭代
   // Stop iterating after leave
   if (leaveReturn === false) {
        return leaveReturn;
    }
 } 
  
 export function walk(ast: INode[], options: WalkOptions) { 
   for (let i = 0; i < ast.length; i++) { 
     let visitReturn = visit(ast[i], void 0, i, options);
     //  Stop iteration  
     if (visitReturn === false) {
        break;
     }
   } 
 }
```

**Comment by Dan-Do** [comment]
It would be great if the css selector is included.
