### ISSUE TITLE
Option for storing attributes as a map/object

### ISSUE THREAD

**Issue by edusperoni** [acrazing/html5parser#2]
Hello!

First of all, amazing work! We're doing some html parsing and this lightweight lib is just what we needed.

I'm proposing an option to add attributes to a named map, so they can be accessed by `attributes.class`, so less time is spend iterating arrays just to find specific attributes.

Maybe this could be a parse option
```
parse(input, {
    generateAttributeArray: false, // default true
    generateAttributeMap: true // default false
}
```

I'm willing to put the effort in a PR once the idea is accepted

**Comment by acrazing** [comment]
Well, I added an option `setAttributeMap` for `parse` API, you can see it at <https://github.com/acrazing/html5parser#api>.

You can use it like:

```ts
const ast = parse('<div id="foo"></div>', { setAttributeMap: true })

console.log(ast[0].attributesMap.id.value.value) // => foo
```
You can get a full example at https://github.com/acrazing/html5parser/blob/master/src/parse.spec.ts#L376.

**Comment by edusperoni** [comment]
Awesome! Thanks a lot!
